/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/cartridge/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cartridge(props) {
  const { nodes, materials } = useGLTF('/models/cartridge/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Poliigon_PlasticMoldWorn_7486_512} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/models/cartridge/model.glb');